# Generated by Django 4.1.4 on 2022-12-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test_single',
        ),
    ]
